# Generated by Django 5.2.6 on 2025-10-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_seen_intro',
        ),
    ]
