# Generated by Django 5.2.8 on 2025-11-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='is_created',
            new_name='created_at',
        ),
    ]
