# Generated by Django 5.2.6 on 2025-10-13 18:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
