# Generated by Django 5.2.8 on 2026-08-17 14:03

import chatapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_blockeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=chatapp.storage.raw_storage, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(blank=True, null=True, storage=chatapp.storage.image_storage, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=chatapp.storage.image_storage, upload_to='avatars/'),
        ),
    ]
